CREATE TABLE IF NOT EXISTS crm_packetValues (
	id TEXT NOT NULL PRIMARY KEY,
	updateDataId TEXT NOT NULL,
	customerId TEXT NOT NULL,
	current BOOLEAN NOT NULL,
	licensedTo TEXT NOT NULL,
	version TEXT NOT NULL,
	serverOS TEXT NOT NULL,
	serverArch TEXT NOT NULL,
	databaseType TEXT NOT NULL,
	databaseVersion TEXT NOT NULL,
	databaseSchemaVersion TEXT NOT NULL,
	fileDriver TEXT NOT NULL,
	activeUsers INTEGER NOT NULL,
	dailyActiveUsers INTEGER NOT NULL,
	monthlyActiveUsers INTEGER NOT NULL,
	inactiveUserCount INTEGER NOT NULL,
	licenseSupportedUsers TEXT NOT NULL,
	totalPosts BIGINT NOT NULL,
	totalChannels BIGINT NOT NULL,
	totalTeams INTEGER NOT NULL
);
