CREATE TABLE IF NOT EXISTS crm_pluginValues (
	ID TEXT NOT NULL PRIMARY KEY,
	AuditID TEXT NOT NULL,
	CustomerID TEXT NOT NULL,
	Current BOOLEAN NOT NULL,
	PluginID TEXT NOT NULL,
	Version TEXT NOT NULL,
	IsActive BOOLEAN NOT NULL,
	Name TEXT NOT NULL,
	HomePageURL TEXT NOT NULL
);
