CREATE TABLE IF NOT EXISTS crm_packetValues (
	ID TEXT NOT NULL PRIMARY KEY,
	AuditID TEXT NOT NULL,
	CustomerID TEXT NOT NULL,
	Current BOOLEAN NOT NULL,
	LicensedTo TEXT NOT NULL,
	Version TEXT NOT NULL,
	ServerOS TEXT NOT NULL,
	ServerArch TEXT NOT NULL,
	DatabaseType TEXT NOT NULL,
	DatabaseVersion TEXT NOT NULL,
	DatabaseSchemaVersion TEXT NOT NULL,
	FileDriver TEXT NOT NULL,
	ActiveUsers INTEGER NOT NULL,
	DailyActiveUsers INTEGER NOT NULL,
	MonthlyActiveUsers INTEGER NOT NULL,
	InactiveUserCount INTEGER NOT NULL,
	LicenseSupportedUsers TEXT NOT NULL,
	TotalPosts BIGINT NOT NULL,
	TotalChannels BIGINT NOT NULL,
	TotalTeams INTEGER NOT NULL,
	ElasticServerVersion TEXT NOT NULL,
	MetricService TEXT NOT NULL,
	HostingType TEXT NOT NULL,
	DeploymentType TEXT NOT NULL,
	MobileApp TEXT NOT NULL,
  ProductsInUse TEXT NOT NULL,
	SAMLProvider TEXT NOT NULL,
	LDAPProvider TEXT NOT NULL
);
