CREATE TABLE IF NOT EXISTS crm_audit (
	id TEXT PRIMARY KEY,
	customerId TEXT NOT NULL,
	updatedBy TEXT NOT NULL,
	updatedAt BIGINT NOT NULL,
	updateType TEXT NOT NULL,
	path TEXT NOT NULL,
	diff JSONB NOT NULL
);
