CREATE TABLE IF NOT EXISTS crm_customers (
	ID TEXT PRIMARY KEY,
	Name TEXT NOT NULL,
	LastUpdated bigint NOT NULL,
	SalesforceId TEXT DEFAULT '',
	ZendeskId TEXT DEFAULT '',
	CustomerSuccessManager TEXT DEFAULT '',
	AccountExecutive TEXT DEFAULT '',
	TechnicalAccountManager TEXT DEFAULT '',
	ProductManager TEXT DEFAULT '',
	LicensedTo TEXT DEFAULT '',
	SiteUrl TEXT DEFAULT '',
	LicenseType TEXT NOT NULL,
	CustomerChannel TEXT DEFAULT '',
	GDriveLink TEXT DEFAULT '',
	AirGapped BOOLEAN DEFAULT FALSE,
	AirGappedReason TEXT DEFAULT '',
	Region TEXT DEFAULT '',
	Status TEXT DEFAULT '',
	CompanyType TEXT DEFAULT '',
	codeWord TEXT DEFAULT ''
);
