CREATE TABLE IF NOT EXISTS crm_audit (
	ID TEXT PRIMARY KEY,
	CustomerID TEXT NOT NULL,
	UpdatedBy TEXT NOT NULL,
	UpdatedAt BIGINT NOT NULL,
	UpdateType TEXT NOT NULL,
	Path TEXT NOT NULL,
	Diff JSONB NOT NULL
);
